interface Station {
    id: string;
    name: string;
}

interface Stations {
    [line: string]: Station[];
}


const stations: Stations = {
    "1호선": [
        { id: "PSS1M164", name: "다대포해수욕장" },
        { id: "PSS1M163", name: "다대포항" },
        { id: "PSS1M162", name: "낫개" },
        { id: "PSS1M161", name: "신장림" },
        { id: "PSS1M160", name: "장림" },
        { id: "PSS1M159", name: "동매" },
        { id: "PSS101", name: "신평" },
        { id: "PSS102", name: "하단" },
        { id: "PSS103", name: "당리" },
        { id: "PSS104", name: "사하" },
        { id: "PSS105", name: "괴정" },
        { id: "PSS106", name: "대티" },
        { id: "PSS107", name: "서대신" },
        { id: "PSS108", name: "동대신" },
        { id: "PSS109", name: "토성" },
        { id: "PSS110", name: "자갈치" },
        { id: "PSS111", name: "남포" },
        { id: "PSS112", name: "중앙" },
        { id: "PSS113", name: "부산역" },
        { id: "PSS114", name: "초량" },
        { id: "PSS115", name: "부산진" },
        { id: "PSS116", name: "좌천" },
        { id: "PSS117", name: "범일" },
        { id: "PSS118", name: "범내골" },
        { id: "PSS119", name: "서면" },
        { id: "PSS120", name: "부전" },
        { id: "PSS121", name: "양정" },
        { id: "PSS122", name: "시청" },
        { id: "PSS123", name: "연산" },
        { id: "PSS124", name: "교대" },
        { id: "PSS125", name: "동래" },
        { id: "PSS126", name: "명륜" },
        { id: "PSS127", name: "온천장" },
        { id: "PSS128", name: "부산대" },
        { id: "PSS129", name: "장전" },
        { id: "PSS130", name: "구서" },
        { id: "PSS131", name: "두실" },
        { id: "PSS132", name: "남산" },
        { id: "PSS133", name: "범어사" },
        { id: "PSS134", name: "노포" },
    ],
    "2호선": [
        { id: "PSS201", name: "장산" },
        { id: "PSS202", name: "중동" },
        { id: "PSS203", name: "해운대" },
        { id: "PSS204", name: "동백" },
        { id: "PSS205", name: "벡스코" },
        { id: "PSS206", name: "센텀시티" },
        { id: "PSS207", name: "민락" },
        { id: "PSS208", name: "수영" },
        { id: "PSS209", name: "광안" },
        { id: "PSS210", name: "금련산" },
        { id: "PSS211", name: "남천" },
        { id: "PSS212", name: "경성대·부경대" },
        { id: "PSS213", name: "대연" },
        { id: "PSS214", name: "못골" },
        { id: "PSS215", name: "지게골" },
        { id: "PSS216", name: "문현" },
        { id: "PSS217", name: "국제금융센터·부산은행" },
        { id: "PSS218", name: "전포" },
        { id: "PSS219", name: "서면" },
        { id: "PSS220", name: "부암" },
        { id: "PSS221", name: "가야" },
        { id: "PSS222", name: "동의대" },
        { id: "PSS223", name: "개금" },
        { id: "PSS224", name: "냉정" },
        { id: "PSS225", name: "주례" },
        { id: "PSS226", name: "감전" },
        { id: "PSS227", name: "사상" },
        { id: "PSS228", name: "덕포" },
        { id: "PSS229", name: "모덕" },
        { id: "PSS230", name: "모라" },
        { id: "PSS231", name: "구남" },
        { id: "PSS232", name: "구명" },
        { id: "PSS233", name: "덕천" },
        { id: "PSS234", name: "수정" },
        { id: "PSS235", name: "화명" },
        { id: "PSS236", name: "율리" },
        { id: "PSS237", name: "동원" },
        { id: "PSS238", name: "금곡" },
        { id: "PSS239", name: "호포" },
        { id: "PSS240", name: "증산" },
        { id: "PSS241", name: "부산대양산캠퍼스" },
        { id: "PSS242", name: "남양산" },
        { id: "PSS243", name: "양산" },
    ],
    "3호선": [
        { id: "PSS301", name: "수영" },
        { id: "PSS302", name: "망미" },
        { id: "PSS303", name: "배산" },
        { id: "PSS304", name: "물만골" },
        { id: "PSS305", name: "연산" },
        { id: "PSS306", name: "거제" },
        { id: "PSS307", name: "종합운동장" },
        { id: "PSS308", name: "사직" },
        { id: "PSS309", name: "미남" },
        { id: "PSS310", name: "만덕" },
        { id: "PSS311", name: "남산정" },
        { id: "PSS312", name: "숙등" },
        { id: "PSS313", name: "덕천" },
        { id: "PSS314", name: "구포" },
        { id: "PSS315", name: "강서구청" },
        { id: "PSS316", name: "체육공원" },
        { id: "PSS317", name: "대저" },
    ],
    "4호선": [
        { id: "PSS401", name: "미남" },
        { id: "PSS402", name: "동래" },
        { id: "PSS403", name: "수안" },
        { id: "PSS404", name: "낙민" },
        { id: "PSS405", name: "충렬사" },
        { id: "PSS406", name: "명장" },
        { id: "PSS407", name: "서동" },
        { id: "PSS408", name: "금사" },
        { id: "PSS409", name: "반여농산물시장" },
        { id: "PSS410", name: "석대" },
        { id: "PSS411", name: "영산대" },
        { id: "PSS412", name: "윗반송" },
        { id: "PSS413", name: "고촌" },
        { id: "PSS414", name: "안평" },
    ],
    부산김해경전철: [
        { id: "PSS1001", name: "사상" },
        { id: "PSS1002", name: "괘법르네시떼" },
        { id: "PSS1003", name: "서부산유통지구" },
        { id: "PSS1004", name: "공항" },
        { id: "PSS1005", name: "덕두" },
        { id: "PSS1006", name: "등구" },
        { id: "PSS1007", name: "대저" },
        { id: "PSS1008", name: "평강" },
        { id: "PSS1009", name: "대사" },
        { id: "PSS1010", name: "불암" },
        { id: "PSS1011", name: "지내" },
        { id: "PSS1012", name: "김해대학" },
        { id: "PSS1013", name: "인제대" },
        { id: "PSS1014", name: "김해시청" },
        { id: "PSS1015", name: "부원" },
        { id: "PSS1016", name: "봉황" },
        { id: "PSS1017", name: "수로왕릉" },
        { id: "PSS1018", name: "박물관" },
        { id: "PSS1019", name: "연지공원" },
        { id: "PSS1020", name: "장신대" },
        { id: "PSS1021", name: "가야대" },
    ],
    동해선: [
        { id: "PSS11M144", name: "부전" },
        { id: "PSS11M145", name: "거제해맞이" },
        { id: "PSS11M146", name: "거제" },
        { id: "PSS11M147", name: "교대" },
        { id: "PSS11M148", name: "동래" },
        { id: "PSS11M149", name: "안락" },
        { id: "PSS11M150", name: "부산원동" },
        { id: "PSS11M151", name: "재송" },
        { id: "PSS11M152", name: "센텀" },
        { id: "PSS11M153", name: "벡스코" },
        { id: "PSS11M154", name: "신해운대" },
        { id: "PSS11M155", name: "송정" },
        { id: "PSS11M156", name: "기장" },
        { id: "PSS11M157", name: "일광" },
        { id: "PSS11M248", name: "좌천" },
        { id: "PSS11M249", name: "월내" },
        { id: "PSS11M250", name: "서생" },
        { id: "PSS11M251", name: "남창" },
        { id: "PSS11M252", name: "망양" },
        { id: "PSS11M253", name: "덕하" },
        { id: "PSS11M254", name: "개운포" },
        { id: "PSS11M255", name: "태화강" },
    ],
};

export default stations;
